### PR TITLE
Change fuse logos

### PR DESCRIPTION
**Pull request by ivan-unfolds**
Updated the logos for current fusiliers and added build command for running locally.

### CODE REVIEW

**Review by andrewMacmurray — CHANGES_REQUESTED** [review]
Looks good, maybe just add a few more instructions for installing / running locally (I know this is probably obvious what to do for us all but for any new people coming on or wanting to make changes it's super useful)

**Review by suninthesky — COMMENTED** [review]
Agree with @andrewMacmurray

**Comment by ivan-unfolds** [comment]
@andrewMacmurray Have now added instructions for running locally.

**Review by andrewMacmurray — APPROVED** [review]

**Comment by andrewMacmurray** [comment]
Boom 💥 , looks great

**Pull request merged**
