### PR TITLE
Spacing of Get Involved fixed

### PR DESCRIPTION
**Pull request by eghale**
Not sure why I can't merge this into Staging but it said ellie was already up to date with that.

### CODE REVIEW

**Comment by andrewMacmurray** [comment]
@eghale have you committed your changes?

**Comment by eghale** [comment]
@andrewMacmurray I thought so..

On branch ellie
Your branch is up-to-date with 'origin/ellie'.
nothing to commit, working tree clean

**Comment by eghale** [comment]
Is there a way to just COMMIT ALL THE THINGS to the master branch and push it? Pretty sure it's all fine... (famous last words..)

**Comment by andrewMacmurray** [comment]
@eghale ah, you've done the branch merges the wrong way round, the `base` branch is staging and you need to merge `ellie` into it

**Comment by andrewMacmurray** [comment]
we'll close this pr and can you open a new one with the branches the other way round?

**Pull request closed without merging**
