### PR TITLE
bug fixes

### LINKED ISSUE #138: Bug fixes on Fuse site
@ivanmauricio @andrewMacmurray 

1) 'Graduates' modal quotes should be formatted the same for each box - see discrepancy below

screen shot 2017-03-21 at 11 15 45
screen shot 2017-03-21 at 11 15 32

2) Oxfam, Breast Cancer Care, Age UK and Centrepoint should all be on the first line together (as they were the first cohort) and Women's Aid, Advising London and Clore on the second line together

3) Parkinson's UK logo is weirdly squished, could you find a better one/unsquish it?
screen shot 2017-03-21 at 11 23 25

4) Women's Aid logo seems smaller/lower res than the others, could you find a better quality version?
screen shot 2017-03-21 at 11 18 06

5) Super Being Labs should really be in the 'Supporters and Partners' section, not 'The Team' section. Also we need to add a Health Foundry logo to 'Supporters and Partners' as well.

### PR DESCRIPTION
**Pull request by andrewMacmurray**
change logos for parkinsons and womens aid, remove ems on quote, move partners to different lines, move sam and ellie in team

closes #138

### CODE REVIEW

**Review by ivan-unfolds — APPROVED** [review]
Looks great!

**Comment by eghale** [comment]
Couple of things - this line in Oxfam's modal shouldn't be italics as it's not part of the quote: Oxfam is currently looking at the best way to fund the future development of this service, identifying potential routes to support the next steps of the project.

Also the staging site is still showing the old format for quotes in the second line of charities (i.e. not italics).

**Comment by eghale** [comment]
And is there an img class that the Super Being Labs logo isn't inheriting that the others are? They all seem to be a uniform length (115.94) but that one's longer. Code looks the same so perhaps might just be the image size itself?

Noticed the same issue with the FAC and Esmee logos on the main page.

**Comment by andrewMacmurray** [comment]
@eghale for future reference, these comments should go on the original issue not a closed pr.

**Pull request merged**
